import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'logo_text1': "Campus",
          'logo_text2': "Link",
          'email': 'Email',
          'login': 'Login',
          'signup': 'Sign Up',
          'password': 'Password',
          'internet_exception':
              "We're unable tp show results.\nPlease check your data\nconenction.",
          'general_exception':
              "We're unable to process your request.\n Please try again",
          'welcome_back': 'Welcome\nBack',
          'login_to_portal': 'Login to Portal',
          'student_id': 'Student ID',
          'teacher_id': 'Teacher ID',
          'id_hint': 'Enter your student id',
          'sign_up_as_teacher': 'Sign up as teacher',
          'sign_up_as_student': 'Sign up as ttudent',
          'email_hint': 'Enter your email',
          'name': 'Name',
          'name_hint': 'Enter your name',
          'cnic': 'CNIC',
          'cnic_hint': 'Enter your CNIC',
          'phone': 'Phone',
          'phone_hint': 'Enter your phone',
          'department': 'Department',
          'department_hint': 'Select department',
          'roll_no': 'Roll no',
          'roll_no_hint': 'e.g (123456)',
          'semester': 'Semester',
          'semester_hint': 'e.g 2nd',
          'program': 'Program',
          'program_hint': 'e.g (BS, ADP)',
          'session': 'Session',
          'session_hint': 'e.g (2022-26)',
          'courses': 'Courses',
          'timetable': 'TimeTable',
          'notifications': 'Notifications',
          'complaint': 'Complaint',
          'transport': 'Transport',
          'recent_complaints': 'Recent Complaints',
          'forget_password': 'Forget Password',
          'sign_out': 'Sign Out',
          'batch': 'Batch',
          'batch_hint': 'Select batch',
          'father_name': "Father Name",
          'father_name_hint': "Enter father name",
          'dob_hint': "Select date of birth",
          'dob': "Date of birth",
          'address_hint': "Enter complete address",
          'address': "Address",
          'city': "City",
          'city_hint': "Enter your city",
          'state_hint': "Enter your state",
          'state': "State",
          'send_email': "Send Email",
          'time_table': "Time Table",
        },
        'ur_PK': {},
      };
}
