// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACk7llwqrZHwMHmNlJ5GD-K1_LwGn5h9Y',
    appId: '1:495585436205:web:3c44bd53b69ab2d7d6cea4',
    messagingSenderId: '495585436205',
    projectId: 'campuslink-a2d2d',
    authDomain: 'campuslink-a2d2d.firebaseapp.com',
    storageBucket: 'campuslink-a2d2d.appspot.com',
    measurementId: 'G-TWTPRYKVWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1QyXuh-r2LslWXbshCxBRdS6zAELoIE',
    appId: '1:495585436205:android:b14f264ece9c0bacd6cea4',
    messagingSenderId: '495585436205',
    projectId: 'campuslink-a2d2d',
    storageBucket: 'campuslink-a2d2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRf6-FvQM5Lgkj1Ok4lUMAa0QK1qiRugU',
    appId: '1:495585436205:ios:479a8f19d7fad44bd6cea4',
    messagingSenderId: '495585436205',
    projectId: 'campuslink-a2d2d',
    storageBucket: 'campuslink-a2d2d.appspot.com',
    iosBundleId: 'com.example.campuslinkMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRf6-FvQM5Lgkj1Ok4lUMAa0QK1qiRugU',
    appId: '1:495585436205:ios:479a8f19d7fad44bd6cea4',
    messagingSenderId: '495585436205',
    projectId: 'campuslink-a2d2d',
    storageBucket: 'campuslink-a2d2d.appspot.com',
    iosBundleId: 'com.example.campuslinkMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACk7llwqrZHwMHmNlJ5GD-K1_LwGn5h9Y',
    appId: '1:495585436205:web:1396266f56b154b1d6cea4',
    messagingSenderId: '495585436205',
    projectId: 'campuslink-a2d2d',
    authDomain: 'campuslink-a2d2d.firebaseapp.com',
    storageBucket: 'campuslink-a2d2d.appspot.com',
    measurementId: 'G-L3LPSB2TYJ',
  );
}
